# Generated by Django 4.2.16 on 2026-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('hr', 'HR'), ('manager', 'Quản lý'), ('employee', 'Nhân viên')], default='employee', max_length=20, verbose_name='Vai trò'),
        ),
    ]
