#!/bin/bash
# HRM System - Start Script
cd "$(dirname "$0")"

echo "================================================================"
echo "   HRM System - Khởi động server"
echo "================================================================"
echo ""
echo "  URL:   http://127.0.0.1:8000"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │         DANH SÁCH TÀI KHOẢN MẪU  (mật khẩu: 123456)   │"
echo "  ├────────────────────────┬─────────────┬──────────────────┤"
echo "  │ Tài khoản              │ Vai trò     │ Họ tên           │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ admin                  │ admin       │ (superuser)      │"
echo "  │   pw: admin123         │             │                  │"
echo "  │ hr                     │ hr          │ (superuser)      │"
echo "  │   pw: hr123456         │             │                  │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ admin_demo             │ admin       │ Admin Demo       │"
echo "  │ hr_demo                │ hr          │ HR Demo          │"
echo "  │ dinh.thi.j             │ hr          │ Đinh Thị Jade    │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ manager_it             │ manager     │ Nguyễn Văn Khoa  │"
echo "  │ manager_sale           │ manager     │ Trần Quốc Hùng   │"
echo "  │ manager_hr             │ manager     │ Phạm Thị Lan     │"
echo "  │ do.van.g               │ manager     │ Đỗ Văn Gia       │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ nguyen.van.a           │ employee    │ Nguyễn Văn An    │"
echo "  │ tran.thi.b             │ employee    │ Trần Thị Bình    │"
echo "  │ le.van.c               │ employee    │ Lê Văn Cường     │"
echo "  │ pham.thi.d             │ employee    │ Phạm Thị Dung    │"
echo "  │ hoang.van.e            │ employee    │ Hoàng Văn Em     │"
echo "  │ vu.thi.f               │ employee    │ Vũ Thị Fư        │"
echo "  │ bui.thi.h              │ employee    │ Bùi Thị Hoa      │"
echo "  │ dang.van.i             │ employee    │ Đặng Văn Ích     │"
echo "  └────────────────────────┴─────────────┴──────────────────┘"
echo "  Tất cả mật khẩu: 123456  (trừ admin/hr ở trên)"
echo ""
echo "  Nhấn Ctrl+C để dừng server."
echo "================================================================"
echo ""

./venv/bin/python manage.py runserver
