# Generated by Django 4.2.16 on 2026-05-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Thư xin việc')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('screening', 'Đang sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('referral', 'Giới thiệu'), ('agency', 'Agency'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nguồn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
            ],
            options={
                'verbose_name': 'Ứng viên',
                'verbose_name_plural': 'Ứng viên',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(blank=True, verbose_name='Yêu cầu')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Lương tối thiểu')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Lương tối đa')),
                ('vacancies', models.PositiveIntegerField(default=1, verbose_name='Số lượng tuyển')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang tuyển'), ('closed', 'Đã đóng')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Hạn nộp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='employees.department', verbose_name='Phòng ban')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='employees.position', verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Tin tuyển dụng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Thời gian phỏng vấn')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Thời lượng (phút)')),
                ('interview_type', models.CharField(choices=[('phone', 'Phỏng vấn điện thoại'), ('online', 'Phỏng vấn online'), ('in_person', 'Phỏng vấn trực tiếp')], default='in_person', max_length=20, verbose_name='Hình thức')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('feedback', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Đánh giá (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.candidate', verbose_name='Ứng viên')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn')),
            ],
            options={
                'verbose_name': 'Phỏng vấn',
                'verbose_name_plural': 'Phỏng vấn',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='applied_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobposting', verbose_name='Vị trí ứng tuyển'),
        ),
    ]
