# Generated by Django 4.2.16 on 2026-05-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loại nghỉ phép')),
                ('days_per_year', models.PositiveIntegerField(default=12, verbose_name='Số ngày/năm')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Có hưởng lương')),
            ],
            options={
                'verbose_name': 'Loại nghỉ phép',
                'verbose_name_plural': 'Loại nghỉ phép',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca làm việc')),
                ('monday', models.BooleanField(default=True, verbose_name='Thứ 2')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Thứ 3')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Thứ 4')),
                ('thursday', models.BooleanField(default=True, verbose_name='Thứ 5')),
                ('friday', models.BooleanField(default=True, verbose_name='Thứ 6')),
                ('saturday', models.BooleanField(default=False, verbose_name='Thứ 7')),
                ('sunday', models.BooleanField(default=False, verbose_name='Chủ nhật')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('break_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Thời gian nghỉ (phút)')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Từ ngày')),
                ('end_date', models.DateField(verbose_name='Đến ngày')),
                ('days_count', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Số ngày')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.leavetype', verbose_name='Loại nghỉ phép')),
            ],
            options={
                'verbose_name': 'Đơn nghỉ phép',
                'verbose_name_plural': 'Đơn nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ngày được phân bổ')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ngày đã dùng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Nhân viên')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.leavetype', verbose_name='Loại nghỉ phép')),
            ],
            options={
                'verbose_name': 'Số dư nghỉ phép',
                'verbose_name_plural': 'Số dư nghỉ phép',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi muộn'), ('half_day', 'Nửa ngày'), ('leave', 'Nghỉ phép')], default='present', max_length=20, verbose_name='Trạng thái')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Số giờ làm việc')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bản ghi chấm công',
                'verbose_name_plural': 'Bản ghi chấm công',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
