# Generated by Django 4.2.16 on 2026-05-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại bảo hiểm')),
                ('employee_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tỷ lệ NLĐ (%)')),
                ('employer_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tỷ lệ NSDLĐ (%)')),
                ('effective_from', models.DateField(verbose_name='Hiệu lực từ ngày')),
            ],
            options={
                'verbose_name': 'Mức đóng bảo hiểm',
                'verbose_name_plural': 'Mức đóng bảo hiểm',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu trúc lương')),
                ('basic_salary_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='% lương cơ bản')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Cấu trúc lương',
                'verbose_name_plural': 'Cấu trúc lương',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cơ bản')),
                ('allowances_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng phụ cấp')),
                ('deductions_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng khấu trừ')),
                ('net_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương thực lĩnh')),
                ('working_days', models.PositiveIntegerField(default=0, verbose_name='Ngày công chuẩn')),
                ('actual_working_days', models.PositiveIntegerField(default=0, verbose_name='Ngày công thực tế')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt'), ('paid', 'Đã thanh toán')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DeductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khấu trừ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_items', to='payroll.payroll', verbose_name='Bảng lương')),
            ],
            options={
                'verbose_name': 'Khoản khấu trừ',
                'verbose_name_plural': 'Khoản khấu trừ',
            },
        ),
        migrations.CreateModel(
            name='AllowanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phụ cấp')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_items', to='payroll.payroll', verbose_name='Bảng lương')),
            ],
            options={
                'verbose_name': 'Khoản phụ cấp',
                'verbose_name_plural': 'Khoản phụ cấp',
            },
        ),
    ]
