# Generated by Django 4.2.16 on 2026-05-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng ban')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng ban')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng phòng')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chức vụ')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã chức vụ')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], default='junior', max_length=20, verbose_name='Cấp độ')),
                ('salary_grade', models.CharField(blank=True, max_length=20, verbose_name='Hệ số lương')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name='Phòng ban')),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Chức vụ',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='CCCD/CMND')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('employment_type', models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('contract', 'Hợp đồng')], default='full_time', max_length=20, verbose_name='Loại hình làm việc')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ việc')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Tên người liên hệ khẩn cấp')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT liên hệ khẩn cấp')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='Số tài khoản')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Phòng ban')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Chức vụ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('fixed_term', 'Có thời hạn'), ('indefinite', 'Không thời hạn'), ('part_time', 'Bán thời gian')], max_length=20, verbose_name='Loại hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cơ bản')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Ngày ký')),
                ('status', models.CharField(choices=[('active', 'Đang hiệu lực'), ('expired', 'Hết hạn'), ('terminated', 'Đã chấm dứt')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-start_date'],
            },
        ),
    ]
